modmap:
  - name: Esc to Capslock
    remap:
      ESC: CapsLock
  - name: Capslock to esc/ctrl
    remap:
      CapsLock:
        held: CTRL_L
        alone: ESC
        alone_timeout_millis: 150
  - name: Enter is super when held
    remap:
      ENTER:
        held: SUPER_L
        alone: ENTER
        # alone_timeout_millis: 150
