### SETTINGS ###

theme = "gruvbox_dark_hard"

[editor]
bufferline    = "multiple"         # show tab bar if multiple buffers are open
line-number   = "relative"         # relative
color-modes   = true               # change mode indicator colors
shell         = ["zsh", "-c"]      # execute shell commands with zsh
rulers        = [81]               # highlight 81st column
cursorline    = true               # highlight lines with cursors
soft-wrap     = { enable = true }  # wrap lines instead of extending them off screen
file-picker   = { hidden = false } # Show .files in file picker
indent-guides = { render = true }  # Show indentation guides

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

### BINDINGS ###

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
D   = "kill_to_line_end"

[keys.normal."space".w]
c = "wclose"

[keys.normal."minus"]
o = ":pipe xargs -n 1 open" # "open" Can work on many things...

# (G)it
[keys.normal."minus".g]
g = ":sh tmux display-popup -h 90% -w 80% -E lazygit"
# Can't do things like "Open short git diff for current file"
# until helix implements better ex-mode variables
# Would need "current file path relative to project root"

# (C)ode
[keys.normal."minus".c]
# Prompt chat gpt
p = ":pipe cgpt"
# Prompt chat gpt to write code
r = ":pipe cgpt --code"

# misc (E)xternal program pipes
[keys.normal."minus".e]
f = [":pipe fmt"] # Format selection as paragraph
d = [":insert-output date +'%B %d, %Y'"]

# (B)uffer
[keys.normal."minus".b]
c = ":bc"     # Close buffer
s = ":w"      # Save buffer
r = ":reload" # Reload buffer
S = ":wa"     # Save all buffers
n = ":bn"     # next buffer
p = ":bp"     # previous buffer

# (C)onfig
[keys.normal."minus".C]
o = ":config-open"   # Open helix config
r = ":config-reload" # Reload helix config

# (H)elp
[keys.normal."minus".h]
# Open helix docs in browser
h = ":sh open https://docs.helix-editor.com/" 
# lazygit bindings
g = ":sh open https://github.com/jesseduffield/lazygit/blob/master/docs/keybindings/Keybindings_en.md#lazygit-keybindings"
# Kitty (terminal) documentation
k = ":sh open https://sw.kovidgoyal.net/kitty/overview/#"

# (T)mux bindings
# TODO: binding for opening temporary lf or lg sessions
[keys.normal."minus".t]
# lazygit popup
t = [":sh tmux send-keys -t :.! !! C-m"]